
---

#the positions of the join sign
sign_join_x: 
sign_join_y: 
sign_join_z:
sign_world: "world"

#the positions of the side's enter places.
blue_enter_x: 
blue_enter_y: 
blue_enter_z: 

red_enter_x: 
red_enter_y: 
red_enter_z: 

#the place where players teleport to when the game is starting soon
waiting_x: 
waiting_y: 
waiting_z: 

#the items that will be given to the players when the game starts
items:
 - 90

#the message will be sent to the player when the boat race is full
teams_are_full_message: "boat race is full"

#the level that we'll get it's spawn and teleport the player to it when the game ends
spawn_level: "world"
...
